#!/usr/bin/env python3
"""Guard against AI attribution in git commits (boil hard rule 20).

Why this exists: a `Co-Authored-By: Claude ...` trailer makes GitHub list the
AI as a repo Contributor. Amending + force-pushing does NOT fix it — GitHub
retains the old commit as an unreachable object and cache rebuilds (rename,
visibility change, new push) keep resurrecting the contributor entry. The only
reliable cleanups are repo delete+recreate or a GitHub Support purge. So the
trailer must never be committed in the first place.

Modes:
    boil-commit-guard.py [--root DIR] [--range REV_RANGE]
        Scan commits (default: unpushed commits on the current branch, or the
        last 50 if no upstream) for AI trailers and AI author/committer
        identities. Exit 1 with remediation guidance if any are found.

    boil-commit-guard.py --check-message FILE
        Validate a single commit message file (used by the commit-msg hook).

    boil-commit-guard.py --install-hook [--root DIR]
        Install a commit-msg hook that rejects offending messages at commit
        time. Idempotent; chains an existing non-boil hook by backing it up
        and calling it first.
"""
from __future__ import annotations

import argparse
import os
import re
import stat
import subprocess
import sys
from pathlib import Path

AI_PATTERN = re.compile(
    r"(co-authored-by|generated with|generated by|authored-by)[^\n]*"
    r"(claude|codex|chatgpt|gpt-|copilot|gemini|cursor|anthropic|openai|"
    r"noreply@anthropic\.com|users\.noreply\.github\.com.*\bbot\b|\[bot\])",
    re.IGNORECASE,
)
AI_IDENTITY = re.compile(
    r"(claude|codex|chatgpt|copilot|gemini|anthropic|openai|\[bot\])",
    re.IGNORECASE,
)

HOOK_MARKER = "# boil-commit-guard hook"
HOOK_BODY = f"""#!/bin/sh
{HOOK_MARKER}
python3 "{{guard_path}}" --check-message "$1" || exit 1
{{chain}}
"""


def git(root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True, text=True, check=True,
    ).stdout


def scan_message(text: str) -> list[str]:
    return [m.group(0).strip() for m in AI_PATTERN.finditer(text)]


def default_range(root: Path) -> str:
    try:
        upstream = git(root, "rev-parse", "--abbrev-ref", "@{upstream}").strip()
        return f"{upstream}..HEAD"
    except subprocess.CalledProcessError:
        return "-50"


def scan_commits(root: Path, rev_range: str) -> int:
    log_args = ["log", "--format=%H%x00%an <%ae>%x00%cn <%ce>%x00%B%x01"]
    log_args.append(rev_range) if not rev_range.startswith("-") else log_args.insert(1, rev_range)
    try:
        raw = git(root, *log_args)
    except subprocess.CalledProcessError as exc:
        print(f"git log failed: {exc.stderr or exc}", file=sys.stderr)
        return 2

    findings = []
    for record in filter(None, (r.strip("\n") for r in raw.split("\x01"))):
        sha, author, committer, message = record.lstrip("\n").split("\x00", 3)
        for hit in scan_message(message):
            findings.append((sha[:8], f"trailer: {hit}"))
        for role, ident in (("author", author), ("committer", committer)):
            if AI_IDENTITY.search(ident):
                findings.append((sha[:8], f"{role} identity: {ident}"))

    if not findings:
        print(f"OK: no AI attribution in commits ({rev_range or 'default range'})")
        return 0

    print("FAIL: AI attribution found in commits:\n")
    for sha, what in findings:
        print(f"  {sha}  {what}")
    print(
        "\nRemediation:\n"
        "  NOT pushed yet : git commit --amend (or interactive-free rebase) to strip it.\n"
        "  Already pushed : force-push alone will NOT remove the contributor on GitHub —\n"
        "                   the old commit survives as an unreachable object. For a fresh\n"
        "                   repo, delete + recreate + push clean history; otherwise ask\n"
        "                   GitHub Support to purge the unreachable commits.\n"
        "  Prevent forever: boil-commit-guard.py --install-hook"
    )
    return 1


def check_message(path: Path) -> int:
    hits = scan_message(path.read_text(encoding="utf-8", errors="replace"))
    if not hits:
        return 0
    print("commit rejected by boil-commit-guard (boil hard rule 20):", file=sys.stderr)
    for hit in hits:
        print(f"  {hit}", file=sys.stderr)
    print("Remove AI co-author/attribution trailers and commit again.", file=sys.stderr)
    return 1


def install_hook(root: Path) -> int:
    hooks_dir = Path(git(root, "rev-parse", "--git-path", "hooks").strip())
    if not hooks_dir.is_absolute():
        hooks_dir = root / hooks_dir
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook = hooks_dir / "commit-msg"
    chain = ""
    if hook.exists():
        existing = hook.read_text(encoding="utf-8", errors="replace")
        if HOOK_MARKER in existing:
            print(f"OK: hook already installed at {hook}")
            return 0
        backup = hook.with_name("commit-msg.pre-boil")
        backup.write_text(existing, encoding="utf-8")
        backup.chmod(backup.stat().st_mode | stat.S_IXUSR)
        chain = f'"{backup}" "$1" || exit 1\n'
        print(f"note: existing hook chained via {backup}")
    guard_path = Path(__file__).resolve()
    hook.write_text(HOOK_BODY.format(guard_path=guard_path, chain=chain), encoding="utf-8")
    hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"OK: installed commit-msg hook at {hook}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=os.getcwd())
    ap.add_argument("--range", dest="rev_range", default=None,
                    help="rev range to scan (default: @{upstream}..HEAD, else last 50)")
    ap.add_argument("--check-message", metavar="FILE",
                    help="validate one commit message file (hook mode)")
    ap.add_argument("--install-hook", action="store_true")
    args = ap.parse_args()

    if args.check_message:
        return check_message(Path(args.check_message))
    root = Path(args.root).resolve()
    if args.install_hook:
        return install_hook(root)
    return scan_commits(root, args.rev_range or default_range(root))


if __name__ == "__main__":
    raise SystemExit(main())
